### PR TITLE
PR of everything we had for the demo

### PR DESCRIPTION
**Pull request by farahwamer**
This just joins search and filter basically

### CODE REVIEW

**Comment by cainsusk** [comment]
@farahwamer 

When I do 

   docker compose build
   docker compose up

and then

   npm start

It shows me the admin dashboard even though I am not an admin.

Screenshot 2024-04-07 at 1 45 46 PM

Also, it seems to not be able to show the items in this state (however Im not sure if that is due to showing the incorrect dashboard)

https://github.com/queens-psyc-clinic/app/assets/63693601/70f200a1-db63-4c70-9ce7-fde7aa44a1b7

**Comment by farahwamer** [comment]
> @farahwamer
> 
> > Note: I am on `Safari`, and it seems to be doing this because it thinks I have an account, bypassing the sign-in page (but I don't have an account in the DB)
> 
> When I do
> 
> ```
>  docker compose build
> 
>  docker compose up
> ```
> 
> and then
> 
> ```
>  npm start
> ```
> 
> It shows me the admin dashboard even though I am not an admin.
> 
> Screenshot 2024-04-07 at 1 45 46 PM
> Also, it seems to not be able to show the items in this state (however Im not sure if that is due to showing the incorrect dashboard)
> 
>  Screen.Recording.2024-04-07.at.1.49.45.PM.mov



> @farahwamer
> 
> > Note: I am on `Safari`, and it seems to be doing this because it thinks I have an account, bypassing the sign-in page (but I don't have an account in the DB)
> 
> When I do
> 
> ```
>  docker compose build
> 
>  docker compose up
> ```
> 
> and then
> 
> ```
>  npm start
> ```
> 
> It shows me the admin dashboard even though I am not an admin.
> 
> Screenshot 2024-04-07 at 1 45 46 PM
> Also, it seems to not be able to show the items in this state (however Im not sure if that is due to showing the incorrect dashboard)
> 
>  Screen.Recording.2024-04-07.at.1.49.45.PM.mov

2 things could be happening here:
1. your browser could still have the user id in local storage from other times you have run the local host on other branches, which is only an issue we run into because we switch branches without logging out (which removes it from the browser). so you can fix this by clearing your history (including your cookies), OR simply going to the settings oage and clicking log out
2. the items are working on my computer, perhaps you still need to pull?

**Comment by cainsusk** [comment]
@farahwamer Ok yup those seemed to be the issues ! thanks !!

**Comment by cainsusk** [comment]
@farahwamer one other thing -- I noticed that the top cards on the admin dashboard:

Screenshot 2024-04-07 at 2 19 03 PM

Still do not show the correct data, and also do not go to the correct pages. Is this addressed in another PR?

**Review by cainsusk — APPROVED** [review]
LGTM ! Thanks for helping resolve the issues I had !

**Review by cainsusk — APPROVED** [review]
Works for me!

**Pull request merged**
