### PR TITLE
Change password

### PR DESCRIPTION
**Pull request by cainsusk**
You can now change the password of users as admin !
Screenshot 2024-03-27 at 8 23 48 PM

Try this ^^^

also the database has been stripped of all trailing/leading spaces!

### CODE REVIEW

**Comment by cainsusk** [comment]
note that "1" is the ID of an admin user for testing

**Comment by cainsusk** [comment]
users can now change their own password !

**Review by farahwamer — APPROVED** [review]
amazing work

**Review by farahwamer — CHANGES_REQUESTED** [review]
for some reason when i merge this into my branch, the adminer stops working and the api doc cant connect to sql

**Comment by cainsusk** [comment]
OK I believe I fixed it

**Review by farahwamer — APPROVED** [review]
NICE

**Pull request merged**
